name: publish

on:
  push:
    tags:
      - v*.*.*

env:
  LOGIN_TOKEN: ${{ secrets.LOGIN_TOKEN }}

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.17.0
          cache: npm

      - run: |
          npm i -g pnpm vsce
          pnpm install
          vsce publish -p $LOGIN_TOKEN
          npm run package

      - uses: softprops/action-gh-release@v1
        with:
          files: |
            *.vsix
