name: publish

on:
  push:
    tags:
      - v*.*.*

env:
  LOGIN_TOKEN: ${{ secrets.LOGIN_TOKEN }}
  TAG: ${{ github.ref }}

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7.9.3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.17.0
          cache: pnpm

      - run: pnpm install --registry https://registry.npmjs.org --frozen-lockfile

      - uses: lannonbr/vsce-action@3.0.0
        with:
          args: |
            publish -p $LOGIN_TOKEN --no-dependencies
            package --no-dependencies

      - uses: softprops/action-gh-release@v1
        with:
          files: |
            Likan-$TAG.vsix
