name: publish

on:
  push:
    tags:
      - v*.*.*

env:
  LOGIN_TOKEN: ${{ secrets.LOGIN_TOKEN }}
  TAG: ${{ github.ref }}

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7.9.3
          run_install: |
            - args: [--global, vsce]

      - id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: pnpm install --frozen-lockfile --registry=https://registry.npmjs.org

      - uses: lannonbr/vsce-action@3.0.0
        with:
          args: "publish -p $LOGIN_TOKEN --no-dependencies"

      - run: vsce package --no-dependencies
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            Likan-$TAG.vsix
