name: publish

on:
  push:
    tags:
      - v*.*.*

env:
  LOGIN_TOKEN: ${{ secrets.LOGIN_TOKEN }}

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.0

      - run: |
          yarn add vsce
          yarn install

      - run: |
          npx vsce ls --no-yarn
          npx vsce publish -p $LOGIN_TOKEN --no-yarn

      - uses: actions/upload-artifact@v2
        continue-on-error: true
        with:
          path: |
            *.vsix
            lib
            src

      - uses: softprops/action-gh-release@v1
        continue-on-error: true
        with:
          files: |
            *.vsix
